title: وليد الخلاقي | Portfolio
description: مطور ويب | مبرمج | مهتم بالتقنية
baseurl: ""
url: "https://waleedalkhulaqi.website"
theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
